# ------------------------------------
# PERFIL: DEV (Desarrollo Local Rápido)
# ------------------------------------

spring: # <-- INICIO ÚNICO DEL BLOQUE SPRING
  datasource:
    url: jdbc:h2:mem:digitalnao-db-dev
    username: sa
    password: '' 
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop 
    show-sql: true
  h2:
    console:
      enabled: true 
      path: /h2-console
  security: # <-- MOVIDO AQUÍ
    user:
      password: naopassword

# Sobrescribe el nivel de log para DEV (Este bloque está bien)
logging:
  level:
    org.hibernate.SQL: DEBUG